FROM maven:3.8.1-openjdk-8

ARG GPG_PRIVATE_KEY
ENV GPG_PRIVATE_KEY=$GPG_PRIVATE_KEY

ARG GPG_PASSPHRASE
ENV GPG_PASSPHRASE=$GPG_PASSPHRASE

ARG MAVEN_USERNAME
ENV MAVEN_USERNAME=$MAVEN_USERNAME

ARG MAVEN_PASSWORD
ENV MAVEN_PASSWORD=$MAVEN_PASSWORD

# 将发布脚本添加到容器中
COPY publish.sh /publish.sh

# 设置可执行权限
RUN chmod +x /publish.sh

# 运行发布脚本
ENTRYPOINT ["/publish.sh"]